package fr.restoflash.api.local.android.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig serializableTransactionDaoConfig;
    private final DaoConfig serializablePaymentDaoConfig;

    private final SerializableTransactionDao serializableTransactionDao;
    private final SerializablePaymentDao serializablePaymentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        serializableTransactionDaoConfig = daoConfigMap.get(SerializableTransactionDao.class).clone();
        serializableTransactionDaoConfig.initIdentityScope(type);

        serializablePaymentDaoConfig = daoConfigMap.get(SerializablePaymentDao.class).clone();
        serializablePaymentDaoConfig.initIdentityScope(type);

        serializableTransactionDao = new SerializableTransactionDao(serializableTransactionDaoConfig, this);
        serializablePaymentDao = new SerializablePaymentDao(serializablePaymentDaoConfig, this);

        registerDao(SerializableTransaction.class, serializableTransactionDao);
        registerDao(SerializablePayment.class, serializablePaymentDao);
    }
    
    public void clear() {
        serializableTransactionDaoConfig.getIdentityScope().clear();
        serializablePaymentDaoConfig.getIdentityScope().clear();
    }

    public SerializableTransactionDao getSerializableTransactionDao() {
        return serializableTransactionDao;
    }

    public SerializablePaymentDao getSerializablePaymentDao() {
        return serializablePaymentDao;
    }

}
